copyright:
  "Copyright \xA9 2016\u20132020 <a href=\"http://www.fontlab.com/\">Fontlab\
  \ Ltd.</a>"
docs_dir: srcdocs/mkdocs
extra:
  author:
    twitter: fontlab
  version: 2020.08.06
extra_css:
  - style/fontlab_pyapi.css
google_analytics:
  - UA-313999-1
  - auto
markdown_extensions:
  - attr_list
  - def_list
  - tables
  - abbr
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences:
      disable_indented_code_blocks: false
      highlight_code: true
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.highlight:
      css_class: highlight
      guess_lang: false
      linenums: false
      noclasses: true
      pygments_style: default
      use_pygments: false
  - pymdownx.inlinehilite:
      css_class: highlight
      style_plain_text: false
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.smartsymbols:
      arrows: true
      care_of: false
      copyright: true
      fractions: true
      notequal: true
      ordinal_numbers: false
      plusminus: true
      registered: true
      trademark: true
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.tilde:
      delete: true
      smart_delete: false
      subscript: false
  - pymdownx.caret:
      insert: true
      smart_insert: true
      superscript: true
nav:
  - Home: index.md
  - typerig:
      - typerig: typerig.md
      - core: typerig.core.md
      - core.base: typerig.core.base.md
      - core.base.message: typerig.core.base.message.md
      - core.fileio: typerig.core.fileio.md
      - core.fileio.cla: typerig.core.fileio.cla.md
      - core.fileio.flc: typerig.core.fileio.flc.md
      - core.fileio.krn: typerig.core.fileio.krn.md
      - core.fileio.nam: typerig.core.fileio.nam.md
      - core.func: typerig.core.func.md
      - core.func.collection: typerig.core.func.collection.md
      - core.func.geometry: typerig.core.func.geometry.md
      - core.func.math: typerig.core.func.math.md
      - core.func.string: typerig.core.func.string.md
      - core.func.transform: typerig.core.func.transform.md
      - core.func.utils: typerig.core.func.utils.md
      - core.objects: typerig.core.objects.md
      - core.objects.array: typerig.core.objects.array.md
      - core.objects.atom: typerig.core.objects.atom.md
      - core.objects.collection: typerig.core.objects.collection.md
      - core.objects.cubicbezier: typerig.core.objects.cubicbezier.md
      - core.objects.delta: typerig.core.objects.delta.md
      - core.objects.line: typerig.core.objects.line.md
      - core.objects.matrix: typerig.core.objects.matrix.md
      - core.objects.point: typerig.core.objects.point.md
      - core.objects.transform: typerig.core.objects.transform.md
      - core.objects.utils: typerig.core.objects.utils.md
      - gui: typerig.gui.md
      - gui.QtGui: typerig.gui.QtGui.md
      - gui.widgets: typerig.gui.widgets.md
      - proxy: typerig.proxy.md
      - proxy.application: typerig.proxy.application.md
      - proxy.application.app: typerig.proxy.application.app.md
      - proxy.application.automat: typerig.proxy.application.automat.md
      - proxy.objects: typerig.proxy.objects.md
      - proxy.objects.base: typerig.proxy.objects.base.md
      - proxy.objects.composer: typerig.proxy.objects.composer.md
      - proxy.objects.contour: typerig.proxy.objects.contour.md
      - proxy.objects.curve: typerig.proxy.objects.curve.md
      - proxy.objects.font: typerig.proxy.objects.font.md
      - proxy.objects.glyph: typerig.proxy.objects.glyph.md
      - proxy.objects.kern: typerig.proxy.objects.kern.md
      - proxy.objects.node: typerig.proxy.objects.node.md
      - proxy.objects.shape: typerig.proxy.objects.shape.md
      - proxy.objects.string: typerig.proxy.objects.string.md
      - proxy.pens: typerig.proxy.pens.md
      - proxy.pens.abstractPen: typerig.proxy.pens.abstractPen.md
      - proxy.pens.outlinePen: typerig.proxy.pens.outlinePen.md
  - fontgate:
      - fontgate: fontgate.md
      - fgAnchor: fontgate.fgAnchor.md
      - fgAnchors: fontgate.fgAnchors.md
      - fgAxes: fontgate.fgAxes.md
      - fgAxis: fontgate.fgAxis.md
      - fgCMaps: fontgate.fgCMaps.md
      - fgCaret: fontgate.fgCaret.md
      - fgCarets: fontgate.fgCarets.md
      - fgCmapRecord: fontgate.fgCmapRecord.md
      - fgCoding: fontgate.fgCoding.md
      - fgComponent: fontgate.fgComponent.md
      - fgComponents: fontgate.fgComponents.md
      - fgContour: fontgate.fgContour.md
      - fgContours: fontgate.fgContours.md
      - fgCuspPoint: fontgate.fgCuspPoint.md
      - fgCuspPoints: fontgate.fgCuspPoints.md
      - pyfgDataOwnerData: fontgate.pyfgDataOwnerData.md
      - fgDesignPosition: fontgate.fgDesignPosition.md
      - fgDeviceRecord: fontgate.fgDeviceRecord.md
      - fgDeviceRecords: fontgate.fgDeviceRecords.md
      - fgExtMapUIntToString: fontgate.fgExtMapUIntToString.md
      - fgFont: fontgate.fgFont.md
      - fgFontHinting: fontgate.fgFontHinting.md
      - fgFontInfo: fontgate.fgFontInfo.md
      - fgFontInfoDict: fontgate.fgFontInfoDict.md
      - fgGaspRecord: fontgate.fgGaspRecord.md
      - fgGaspRecords: fontgate.fgGaspRecords.md
      - fgGlyph: fontgate.fgGlyph.md
      - fgGlyphsR: fontgate.fgGlyphsR.md
      - fgGlyphDict: fontgate.fgGlyphDict.md
      - fgGlyphIDsSet: fontgate.fgGlyphIDsSet.md
      - fgGlyphs: fontgate.fgGlyphs.md
      - fgGroup: fontgate.fgGroup.md
      - fgGroups: fontgate.fgGroups.md
      - fgGuide: fontgate.fgGuide.md
      - fgGuides: fontgate.fgGuides.md
      - fgHint: fontgate.fgHint.md
      - fgHintCommand: fontgate.fgHintCommand.md
      - fgHintCommands: fontgate.fgHintCommands.md
      - fgHints: fontgate.fgHints.md
      - fgKerning: fontgate.fgKerning.md
      - fgKerningGroups: fontgate.fgKerningGroups.md
      - fgKerningObject: fontgate.fgKerningObject.md
      - fgKerningObjectPair: fontgate.fgKerningObjectPair.md
      - fgLayer: fontgate.fgLayer.md
      - fgLayers: fontgate.fgLayers.md
      - fgLib: fontgate.fgLib.md
      - fgMapBytes: fontgate.fgMapBytes.md
      - fgExtMapIntTofgShape: fontgate.fgExtMapIntTofgShape.md
      - fgFlagsDict: fontgate.fgFlagsDict.md
      - fgValuesDict: fontgate.fgValuesDict.md
      - fgIntDict: fontgate.fgIntDict.md
      - fgStringDict: fontgate.fgStringDict.md
      - fgMaster: fontgate.fgMaster.md
      - fgMasters: fontgate.fgMasters.md
      - fgMaxP: fontgate.fgMaxP.md
      - fgMetricsClass: fontgate.fgMetricsClass.md
      - fgMetricsClasses: fontgate.fgMetricsClasses.md
      - fgNametable: fontgate.fgNametable.md
      - fgNode: fontgate.fgNode.md
      - fgNodes: fontgate.fgNodes.md
      - fgOTLayout: fontgate.fgOTLayout.md
      - fgOtInfo: fontgate.fgOtInfo.md
      - fgOtValue: fontgate.fgOtValue.md
      - fgPackages: fontgate.fgPackages.md
      - fgPen: fontgate.fgPen.md
      - fgExtMapUShortToShort: fontgate.fgExtMapUShortToShort.md
      - fgShape: fontgate.fgShape.md
      - fgShapes: fontgate.fgShapes.md
      - fgStem: fontgate.fgStem.md
      - fgStems: fontgate.fgStems.md
      - fgTrueTypePoint: fontgate.fgTrueTypePoint.md
      - fgTrueTypePoints: fontgate.fgTrueTypePoints.md
      - fgTTInterpreter: fontgate.fgTTInterpreter.md
      - fgVdmxRecord: fontgate.fgVdmxRecord.md
      - fgVdmxRecords: fontgate.fgVdmxRecords.md
      - fgVectorBool: fontgate.fgVectorBool.md
      - fgVectorChar: fontgate.fgVectorChar.md
      - fgVectorDouble: fontgate.fgVectorDouble.md
      - fgVectorInt: fontgate.fgVectorInt.md
      - fgVectorUInt16: fontgate.fgVectorUInt16.md
      - fgVectorUInt32: fontgate.fgVectorUInt32.md
      - fgVectorPoint: fontgate.fgVectorPoint.md
      - fgZone: fontgate.fgZone.md
      - fgZones: fontgate.fgZones.md
      - fgOptions: fontgate.fgOptions.md
      - fgOpt_T1Import: fontgate.fgOpt_T1Import.md
      - fgOpt_OTImport: fontgate.fgOpt_OTImport.md
      - fgOpt_UfoFontImport: fontgate.fgOpt_UfoFontImport.md
      - fgOpt_VfbImport: fontgate.fgOpt_VfbImport.md
      - fgOpt_VfbExport: fontgate.fgOpt_VfbExport.md
      - fgOpt_UfoFontExport: fontgate.fgOpt_UfoFontExport.md
      - fgOpt_OTExport: fontgate.fgOpt_OTExport.md
      - fgOpt_T1Export: fontgate.fgOpt_T1Export.md
      - fgOpt_EOTExport: fontgate.fgOpt_EOTExport.md
      - fgOpt_WOFFExport: fontgate.fgOpt_WOFFExport.md
      - fgOpt_Font: fontgate.fgOpt_Font.md
      - fgOpt_KerningOptions: fontgate.fgOpt_KerningOptions.md
      - fgOpt_OTExportFeaFile: fontgate.fgOpt_OTExportFeaFile.md
      - fgOpt_TTAutohint: fontgate.fgOpt_TTAutohint.md
      - fgOpt_T1Autohint: fontgate.fgOpt_T1Autohint.md
      - fgOpt_TTFAutohint: fontgate.fgOpt_TTFAutohint.md
      - fgOpt_AutoMetrics: fontgate.fgOpt_AutoMetrics.md
      - fgOpt_ExpandKerning: fontgate.fgOpt_ExpandKerning.md
      - fgOpt_Optimize: fontgate.fgOpt_Optimize.md
      - fgBitmap: fontgate.fgBitmap.md
      - fgBitmaps: fontgate.fgBitmaps.md
      - fgBitmapsData: fontgate.fgBitmapsData.md
      - fgBrush: fontgate.fgBrush.md
      - fgColor: fontgate.fgColor.md
      - fgCurve: fontgate.fgCurve.md
      - fgFontGateData: fontgate.fgFontGateData.md
      - fgGlyphData: fontgate.fgGlyphData.md
      - fgExtMapUCharToUChar: fontgate.fgExtMapUCharToUChar.md
      - fgMatrix: fontgate.fgMatrix.md
      - fgPoint: fontgate.fgPoint.md
      - fgPointU: fontgate.fgPointU.md
      - fgRect: fontgate.fgRect.md
      - fgRendered: fontgate.fgRendered.md
      - fgTrueTypeData: fontgate.fgTrueTypeData.md
      - fgVector: fontgate.fgVector.md
  - fontlab:
      - fontlab: fontlab.md
      - CurveEx: fontlab.CurveEx.md
      - ExportControl: fontlab.ExportControl.md
      - FaBasicPtr: fontlab.FaBasicPtr.md
      - Interval: fontlab.Interval.md
      - PaintBrush: fontlab.PaintBrush.md
      - TransformFrame: fontlab.TransformFrame.md
      - fgSymbol: fontlab.fgSymbol.md
      - fgSymbolList: fontlab.fgSymbolList.md
      - flAbstractEditor: fontlab.flAbstractEditor.md
      - flAbstractVectorNode: fontlab.flAbstractVectorNode.md
      - flAnchor: fontlab.flAnchor.md
      - flAuditInfo: fontlab.flAuditInfo.md
      - flAxis: fontlab.flAxis.md
      - flBasicTool: fontlab.flBasicTool.md
      - flCanvas: fontlab.flCanvas.md
      - flContour: fontlab.flContour.md
      - flContourInfo: fontlab.flContourInfo.md
      - flContourMarker: fontlab.flContourMarker.md
      - flEvent: fontlab.flEvent.md
      - flExpression: fontlab.flExpression.md
      - flGlyph: fontlab.flGlyph.md
      - flGlyphInfo: fontlab.flGlyphInfo.md
      - flGraphicsInfo: fontlab.flGraphicsInfo.md
      - flGuideLine: fontlab.flGuideLine.md
      - flHintingParameters: fontlab.flHintingParameters.md
      - flInstance: fontlab.flInstance.md
      - flItems: fontlab.flItems.md
      - flLayer: fontlab.flLayer.md
      - flLayerInfo: fontlab.flLayerInfo.md
      - flLocation: fontlab.flLocation.md
      - LocationValue: fontlab.LocationValue.md
      - flMarkerPoint: fontlab.flMarkerPoint.md
      - flMouseEvent: fontlab.flMouseEvent.md
      - flModelProducer: fontlab.flModelProducer.md
      - flNode: fontlab.flNode.md
      - flNodeInfo: fontlab.flNodeInfo.md
      - flObject: fontlab.flObject.md
      - flPackage: fontlab.flPackage.md
      - flPaper: fontlab.flPaper.md
      - flPinPoint: fontlab.flPinPoint.md
      - flPreferences: fontlab.flPreferences.md
      - flProperty: fontlab.flProperty.md
      - flPropertyDouble: fontlab.flPropertyDouble.md
      - flPropertyPoint: fontlab.flPropertyPoint.md
      - flSearchInfo: fontlab.flSearchInfo.md
      - flShape: fontlab.flShape.md
      - flShapeBuilder: fontlab.flShapeBuilder.md
      - flShapeData: fontlab.flShapeData.md
      - flShapeInfo: fontlab.flShapeInfo.md
      - flSnapLine: fontlab.flSnapLine.md
      - flSnapObject: fontlab.flSnapObject.md
      - flStem: fontlab.flStem.md
      - flZone: fontlab.flZone.md
      - flSticker: fontlab.flSticker.md
      - flTextBlock: fontlab.flTextBlock.md
      - flTransform: fontlab.flTransform.md
      - flVectorNode: fontlab.flVectorNode.md
      - flVisualItem: fontlab.flVisualItem.md
      - flWorkspace: fontlab.flWorkspace.md
      - FontMetrics: fontlab.FontMetrics.md
      - GlyphComponent: fontlab.GlyphComponent.md
      - flTTHCommand: fontlab.flTTHCommand.md
      - YPanelManager: fontlab.YPanelManager.md
      - YPanelWidget: fontlab.YPanelWidget.md
      - Info: fontlab.Info.md
      - FontLayer: fontlab.FontLayer.md
      - flSnaps: fontlab.flSnaps.md
      - flModel: fontlab.flModel.md
      - PaintBrushShape: fontlab.PaintBrushShape.md
      - SmartCornerParameters: fontlab.SmartCornerParameters.md
      - AccentInfo: fontlab.AccentInfo.md
      - flLayerAttributes: fontlab.flLayerAttributes.md
  - FL:
      - FL: FL.md
      - Anchor: FL.Anchor.md
      - Canvas: FL.Canvas.md
      - Component: FL.Component.md
      - Dialog: FL.Dialog.md
      - Encoding: FL.Encoding.md
      - EncodingRecord: FL.EncodingRecord.md
      - Feature: FL.Feature.md
      - fl: FL.fl.md
      - Font: FL.Font.md
      - Glyph: FL.Glyph.md
      - Guide: FL.Guide.md
      - Hint: FL.Hint.md
      - Image: FL.Image.md
      - KerningPair: FL.KerningPair.md
      - Link: FL.Link.md
      - Matrix: FL.Matrix.md
      - Node: FL.Node.md
      - Point: FL.Point.md
      - Rect: FL.Rect.md
      - TrueTypeTable: FL.TrueTypeTable.md
      - TTPoint: FL.TTPoint.md
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
repo_url: https://www.fontlab.com/
site_author: Fontlab Ltd.
site_description: FontLab 7 Python API
site_dir: ../docs
site_name: FontLab 7 Python API
theme:
  custom_dir: theme
  logo: https://res.cloudinary.com/fontlab/image/fetch/f_auto,w_48,c_scale/https://www.fontlab.com/img/icon-fontlab-7.png
  name: material
  palette:
    primary: blue grey
use_directory_urls: false
