copyright:
      "Copyright \xA9 2016\u20132020 <a href=\"http://www.fontlab.com/\">Fontlab\
      \ Ltd.</a>"
docs_dir: srcdocs/mkdocs
extra:
      author:
            twitter: fontlab
      version: 2020.08.06
extra_css:
      - style/fontlab_pyapi.css
google_analytics:
      - UA-313999-1
      - auto
markdown_extensions:
      - attr_list
      - def_list
      - tables
      - abbr
      - admonition
      - codehilite
      - pymdownx.betterem:
              smart_enable: all
      - pymdownx.superfences:
              disable_indented_code_blocks: false
              highlight_code: true
      - pymdownx.escapeall:
              hardbreak: true
              nbsp: true
      - pymdownx.highlight:
              css_class: highlight
              guess_lang: false
              linenums: false
              noclasses: true
              pygments_style: default
              use_pygments: false
      - pymdownx.inlinehilite:
              css_class: highlight
              style_plain_text: false
      - pymdownx.magiclink:
              hide_protocol: true
      - pymdownx.mark:
              smart_mark: true
      - pymdownx.smartsymbols:
              arrows: true
              care_of: false
              copyright: true
              fractions: true
              notequal: true
              ordinal_numbers: false
              plusminus: true
              registered: true
              trademark: true
      - pymdownx.tasklist:
              custom_checkbox: false
      - pymdownx.tilde:
              delete: true
              smart_delete: false
              subscript: false
      - pymdownx.caret:
              insert: true
              smart_insert: true
              superscript: true
nav:
      - Home: index.md
      - PythonQt: PythonQt.md
      - Qt: PythonQt.Qt.md
      - QtCore: PythonQt.QtCore.md
      - QtGui: PythonQt.QtGui.md
      - QtOpenGL: PythonQt.QtOpenGL.md
      - QtSvg: PythonQt.QtSvg.md
      - QtUiTools: PythonQt.QtUiTools.md
      - QtXml: PythonQt.QtXml.md
      - QtXmlPatterns: PythonQt.QtXmlPatterns.md
      - private: PythonQt.private.md
plugins:
      - search:
              lang: en
              separator: '[\s\-\.]+'
repo_url: https://www.fontlab.com/
site_author: Fontlab Ltd.
site_description: FontLab 7 PythonQt API
site_dir: ../docs/pythonqt
site_name: FontLab 7 PythonQt API
theme:
      custom_dir: theme
      logo: https://res.cloudinary.com/fontlab/image/fetch/f_auto,w_48,c_scale/https://www.fontlab.com/img/icon-fontlab-7.png
      name: material
      palette:
            primary: blue grey
use_directory_urls: false
